### ISSUE TITLE
Gke-0.19.3-privileged

### ISSUE THREAD

**Issue by tdeheurles** [GoogleCloudPlatform/kube-jenkins-imager#1]
I had some problem upgrading cluster from 0.18/v1beta3 to 0.19/v1.
The privileged parts are not working anymore.

It seems that `privileged` are not working for now on gke. Have a look [here](http://stackoverflow.com/questions/31124368/allow-privileged-containers-in-kubernetes-on-google-container-gke/31125679?noredirect=1#comment50263933_31125679).

**Comment by evandbrown** [comment]
I noticed that this morning and pushed 8230acc43eefc027b68c13faf8aa7b8758832a6a a few hours ago to pin the cluster version to 0.18. The Kubernetes team is aware (https://github.com/GoogleCloudPlatform/kubernetes/issues/9626) about the need for the ability to set allow_privileged on the managed master introduced in 0.19. Until then, 8230acc43eefc027b68c13faf8aa7b8758832a6a should work. Please re-open if not.
