### ISSUE TITLE
Restrict where project can be run is unavailable

### ISSUE THREAD

**Issue by znorris** [GoogleCloudPlatform/kube-jenkins-imager#10]
In the Create Jenkins Job section, step 3, there is no option to select 'Restrict where this project can be run.'

**Comment by codepj** [comment]
I noticed the same thing due to the fact that there are no other nodes.

**Comment by znorris** [comment]
I believe it's because `gcr.io/cloud-solutions-images/jenkins-gcp-leader:master-5ca73a6` in `images.cfg` is the default image for Jenkins leader and doesn't include some setting or plugin. I didn't look into it too deeply. But changing it to `gcr.io/cloud-solutions-images/jenkins-gcp-leader:latest` seems to do the trick.

**Comment by codepj** [comment]
Looks like the "latest" tag no longer exists, but everything seemed to work once up upped the nodes in "cluster_up.sh".  Thanks!

**Comment by evandbrown** [comment]
I rev'd the jenkins-gcp-leader image (https://github.com/GoogleCloudPlatform/jenkins-gcp-leader/commit/62965718636da170892d59fa2a244e8bda485c16) a few hours ago to include the latest version of Jenkins and its plugins. Most important here is moving to Swarm 2 (which was also changed in https://github.com/GoogleCloudPlatform/jenkins-packer-agent).

I updated images.cfg in this repo to reflect these new image IDs. e2e tests passed, but please let me know if you see anything that looks wonky!
