### ISSUE TITLE
Cluster Scopes

### ISSUE THREAD

**Issue by znorris** [GoogleCloudPlatform/kube-jenkins-imager#13]
`https://www.googleapis.com/auth/projecthosting` is not listed as an [available scope](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create). Should this be replaced?

https://github.com/GoogleCloudPlatform/kube-jenkins-imager/blob/master/cluster_up.sh#L43

**Comment by evandbrown** [comment]
That list of available scopes is actually the list of available short aliases. `projecthosting` doesn't have an alias so it's not in that list, but is a valid scope.

In this case, the `projecthosting` scope is required to grant Jenkins access to the project's Cloud Source Repository. If you're not using Cloud Repos, you can definitely remove that scope.

**Comment by znorris** [comment]
:+1: Got it. I wondered as much but I had a hard time finding documentation on it. Is there a more definitive listing than [this](https://developers.google.com/identity/protocols/googlescopes)?
