### ISSUE TITLE
error validating data: unexpected type: object

### ISSUE THREAD

**Issue by maxiplay** [GoogleCloudPlatform/kube-jenkins-imager#18]
Hi, I recently restartup the imager and it seems it does not start correctly anymore.
- Deploying services, controllers, and secrets to Google Container Engine...error validating "../jenkins-secrets/ssl_secrets.yaml": error validating data: unexpected type: object; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by viglesiasce** [comment]
Not seeing this with the latest manifests and Jenkins deployment mechanism.
