### ISSUE TITLE
The resource 'projects/ds-jendo/global/images/jenkins-home-image' already exists

### ISSUE THREAD

**Issue by cognitiaclaeves** [GoogleCloudPlatform/kube-jenkins-imager#21]
When previously putting up cluster with ./cluster-up.sh and then tearing down with ./cluster-down.sh, the image is not deleted, so cluster-up.sh errors out when running.

**Comment by viglesiasce** [comment]
Thanks for the feedback @cognitiaclaeves!! I'll get this patched up ASAP.

**Comment by cognitiaclaeves** [comment]
It may be a little late now, but I wrote some clean-up code while trying to
get the imager to work. I probably don't have the bandwidth to own it, but
I could at least share it with you so that you didn't (necessarily) have to
write it as well?

**Comment by viglesiasce** [comment]
I would happily take a PR that fixes this issue.

**Comment by viglesiasce** [comment]
Should be fixed by #24
