### ISSUE TITLE
Some directories such as "jenkins/k8s/options" are missing in the cluster_up.sh file

### ISSUE THREAD

**Issue by novaicaria83** [GoogleCloudPlatform/kube-jenkins-imager#32]
At line 69, we can see the following code:
**PASSWORD=`openssl rand -base64 15`; echo "Your Jenkins password is $PASSWORD"; sed -i.bak s#CHANGE_ME#$PASSWORD# jenkins/k8s/options**

However, when running $ ./cluster_up.sh, I get the following output:
**sed: can't read jenkins/k8s/options: No such file or directory**
and stops the resource deployment process.

Next, the line with the code **$ kubectl create secret generic jenkins --from-file=jenkins/k8s/options --namespace=jenkins** ends up with an error:

**error: error reading jenkins/k8s/options: no such file or directory**

Why those files and directories were deleted if they're still necessary for the K8s resources setup?

**Comment by viglesiasce** [comment]
This should now be fixed as of #33.

The repository that this tutorial depended on changed its methodology to leverage the upstream Helm chart for Jenkins installation. The procedure in this repo has now been updated to leverage the same.
