### ISSUE TITLE
invalid scope during cluster creation

### ISSUE THREAD

**Issue by piontec** [GoogleCloudPlatform/kube-jenkins-imager#5]
"https://www.googleapis.com/auth/projecthosting"

is no longer a valid scope

**Comment by evandbrown** [comment]
D'oh. This is fixed with today's release of v0.9.68 of the [Google Cloud SDK](https://cloud.google.com/sdk/). You can update to that version with `gcloud components update`. I'll close this, but please re-open if this doesn't resolve, and thanks for reporting!
