### ISSUE TITLE
packer not found 

### ISSUE THREAD

**Issue by Kielan** [GoogleCloudPlatform/kube-jenkins-imager#7]
Not sure where I went wrong here but can't seem to debug it.

I verify that packer is installed in my IP/pluginManager/installed/ on my jenkins instance. Version 1.2 is installed.

I initiate build but error is thrown on line 8 and build fails:
/tmp/hudson6695019037556625862.sh: line 8: packer: command not found

I'm still new to Jenkins so maybe I missed an obvious step that was not in the instructions. Will wait a day and then make a SO post but thought I'd add reference here first.

**Comment by evandbrown** [comment]
Does this happen when following the instructions in the readme, which should be using jenkins-packer-agent:master-6c3e5d7 as the image for the build agent? Or is this a custom build agent you're running?
