### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by jedi132000** [GoogleCloudPlatform/kube-jenkins-imager#9]
https://www.dropbox.com/s/0kffz6oi0ysv0g3/jenkins_kube_packer.PNG?dl=0

Please share some insight, It seems like Chef is holding up the build.

**Comment by evandbrown** [comment]
Woah, thanks for catching that! Pushed [the fix](https://github.com/GoogleCloudPlatform/scalable-resilient-web-app/commit/ec265715506a9241c20cb62e93fbdb35f08946d6) in the related project (was using Ubuntu 14.10, and should have been using 14.04 LTS).

The e2e tests should have caught this. I'm going to leave the issue open while I fix the tests.

**Comment by evandbrown** [comment]
OK, this should be caught in future e2e tests (https://github.com/GoogleCloudPlatform/scalable-resilient-web-app/commit/496378c04c8754c7e2a3254c6d25cd05bfd2e6b3)

Thanks, @jedi132000!

**Comment by jedi132000** [comment]
Build still failing with the same error.

**Comment by evandbrown** [comment]
Hi,

I just walked through the lab again and verified that the changes did fix the problem. In the [Replicate a Repo](https://github.com/GoogleCloudPlatform/kube-jenkins-imager#replicate-a-github-repo) part of the instructions, make sure you pull the latest from https://github.com/GoogleCloudPlatform/scalable-resilient-web-app.git (either by adding a remote, then pulling and merging, or just by re-forking and re-pulling the entire thing). The changes were made to that repository to fix this.
